Python/Django_full/mult_apps/apps/random_app/urls.py
from django.conf.urls import url, include
from views import *


urlpatterns = [
    url(r'^random_app', index, name='home'),
    url(r'^random_word$', random_word, name='random_word'),
    url(r'^reset$', reset, name='reset')
]

Python/Django_full/mult_apps/mult_apps/urls.py
from django.conf.urls import url, include


urlpatterns = [
  

    url(r'^', include('apps.merge_apps.urls', namespace='merge_apps')),
    url(r'^time_control/', include('apps.time_control.urls', namespace='time_control')),
    url(r'^course_app/', include('apps.course_app.urls', namespace='course_app')),
    url(r'^golds/', include('apps.golds.urls', namespace='golds')),
    url(r'^l_r/', include('apps.l_r.urls', namespace='l_r')),
    url(r'^random_app/', include('apps.random_app.urls', namespace='random_app'))
]

Python/Django_full/mult_apps/apps/random_app/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

Python/Django_full/mult_apps/apps/random_app/views.py
from django.shortcuts import render, HttpResponse, redirect
import random
from django.utils.crypto import get_random_string

# Create your views here.
def index(request):

  unique_id = get_random_string(length=14)
  unique_word={"somekey":unique_id}

  if 'counter' in request.session:
    request.session['counter'] += 1
  else:
    request.session['counter'] = 1
  return render(request, 'random_app/index.html', unique_word)

def random_word(request):
  if request.method == "POST":
    return redirect('random_app:home')

def reset(request):
  request.session.clear()
  return redirect('random_app:home')

Python/Django_full/mult_apps/apps/random_app/templates/random_app/index.html
<html>
<head>
  <title>Random word generator</title>
</head>
<body>
  <h1>Random Word Generator</h1>
  <p>Attempt # {{request.session.counter}}</p>
  
  <h1>Your randomly generated word is:</h1>
  <p>Word:  {{ somekey }}</p>


  <form action="{% url 'random_app:random_word' %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="NEW WORD">
  </form>

  <form action="{% url 'random_app:reset' %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="RESET ATTEMPTS">
  </form>
</body>
</html>