Python/Django_full/mult_apps/apps/l_r/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^l_r', views.index, name='home'),
    url(r'^register', views.register, name='register'),
    url(r'^login', views.login, name='login'),
    url(r'^success', views.success, name='success'),
]

Python/Django_full/mult_apps/mult_apps/urls.py
from django.conf.urls import url, include


urlpatterns = [
  

    url(r'^', include('apps.merge_apps.urls', namespace='merge_apps')),
    url(r'^time_control/', include('apps.time_control.urls', namespace='time_control')),
    url(r'^course_app/', include('apps.course_app.urls', namespace='course_app')),
    url(r'^golds/', include('apps.golds.urls', namespace='golds')),
    url(r'^l_r/', include('apps.l_r.urls', namespace='l_r')),
    url(r'^random_app/', include('apps.random_app.urls', namespace='random_app'))
]

Python/Django_full/mult_apps/apps/l_r/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class User(models.Model):
  first_name=models.CharField(max_length=40)
  last_name=models.CharField(max_length=40)
  email=models.CharField(max_length=100)
  password=models.CharField(max_length=1000)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

Python/Django_full/mult_apps/apps/l_r/views.py
from django.shortcuts import render, redirect, HttpResponse

from django.contrib import messages
from .models import User
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
import re
import bcrypt

def badname_regex(name):
  reggie=re.compile(r'^[a-zA-Z]+$')
  if reggie.match(name) is None:
    return True

def index(request):
  return render(request, "l_r/index.html")

def DupEmail(email):
  try:
    User.objects.get(email = email)
    return True
  #tried ValidationError
  except User.DoesNotExist:
    return False

def register(request):
 

  is_valid = True
  first_name = request.POST['first_name']
  last_name = request.POST['last_name']
  email = request.POST['email']
  password = request.POST['password'].encode(encoding="utf-8")
  confirm = request.POST['confirm']
  pw_hash=bcrypt.hashpw(password, bcrypt.gensalt())

  if ValidateEmail(email) != True:
    messages.error(request, 'email address not valid')
    is_valid = False

  if DupEmail(email):
    messages.error(request, 'email address in use')
    is_valid= False

  if badname_regex(first_name) or badname_regex(last_name):
    messages.error(request, 'name must contain letters only')
    return redirect('l_r:home')  
  
  if len(first_name) < 2:
    messages.error(request, 'name must be at least 2 characters long')
    is_valid = False
  if len(last_name) < 2:
    messages.error(request, 'name must be at least 2 characters long')
    is_valid = False

  if len(password) < 8:
    messages.error(request, 'password must be at least 8 characters long')
    is_valid = False
  if password != confirm:
    messages.error(request, 'passwords do not match')
    is_valid = False
    
  if is_valid:

    curr_user= User.objects.create(
      first_name=request.POST['first_name'],
      last_name=request.POST['last_name'],
      email=request.POST['email'],
      password= pw_hash
      )


    request.session['s_first_name']=request.POST['first_name']
    request.session['msg']='registered'

    return redirect('course_app:home')
   

  else:
    return redirect('l_r:home')

  

def login(request):
  l_email=request.POST['l_email']
  try:
    curr_user=User.objects.get(email = l_email)

    # print pw_hash
    # print curr_user.password
    # it's not 'if this hashed password = entered hashed password'
    l_password=request.POST['l_password'].encode(encoding="utf-8")
    if bcrypt.hashpw(l_password, curr_user.password.encode("utf-8")) == curr_user.password:
      request.session['s_first_name']=curr_user.first_name
      request.session['msg']='logged in'
      return redirect('course_app:home')
    else:
      messages.error(request, 'password does not match registered user')
      return redirect('l_r:home')
  except User.DoesNotExist:
    messages.error(request, 'email does not exist in database, please register')
    return redirect('l_r:home')

  pass


def success(request):
  pass
  return render(request, "l_r/success.html")

def ValidateEmail( email ):    
  try:
    validate_email( email )
    return True
  except ValidationError:
    return False


   

Python/Django_full/mult_apps/apps/l_r/templates/l_r/index.html
<html>
<head>
  <title>Login and Registration</title>
</head>
<body>
  <h1>Registration</h1>
  <form action="{% url 'l_r:register' %}" method="POST">
    {% csrf_token %}
    <label>First Name:</label>
    <input type="text" name="first_name"><br>

    <label>Last Name:</label>
    <input type="text" name="last_name"><br>

    <label>Email:</label>
    <input type="email" name="email"><br>
        
    <label>Password:</label>
    <input type="password" name="password"><br>
    

    <label>Confirm Password:</label>
    <input type="password" name="confirm"><br>

    <input type="submit" name="submit" value="Register">
  </form>

  <h1>Login</h1>
  <form action="{% url 'l_r:login' %}" method="POST">
    {% csrf_token %}
    <label>Email:</label>
    <input type="email" name="l_email"><br>

    <label>Password:</label>
    <input type="password" name="l_password"><br>

    <input type="submit" name="submit" value="Login">
  </form>

  {% if messages %}
    {% for message in messages %}
      {{message}}
    {% endfor %}
  {% endif %}



</body>
</html>

Python/Django_full/mult_apps/apps/l_r/templates/l_r/success.html
<html>
<head>
  <title>Success</title>
</head>
<body>
  <h1>Welcome {{request.session.s_first_name}} you have successfully {{request.session.msg}}</h1> 
</body>
</html>